### ISSUE TITLE
假如要讀取txt檔做斷詞

### ISSUE THREAD

**Issue by JeremyCKT** [Droidtown/ArticutAPI#1]
請問一下ArticutAPI.py中，inputSTR那段是否可以改成讀取txt或json檔呢？如果要讀取，指令應該寫什麼呢？
當我把這行改成這樣的時候
inputSTR = open('xxx.txt', 'r')
結果就出現以下的錯誤訊息
TypeError: Object of type TextIOWrapper is not JSON serializable

請問我該如何解決呢？

**Comment by PeterWolf-tw** [comment]
在 Python 裡，open() 一個檔案以後，只是 TextIOWrapper Object 哦。要取得內容的文字的話，要寫做：

`inputSTR = open("xxx.txt", "r").read()`

TextIOWrapper Object 經過 .read() 以後，就會變成 string type 了。(以 Python3 而言，應該是 unicode type)。

json 檔的話，可利用內建的 json 模組。

```
import json
json_content = json.loads(open("xxx.json").read())
```
參考：
https://www.w3schools.com/python/python_file_open.asp
https://pythonbasics.org/read-json-file/
